import {useMemo,useState} from 'react';
import {ArrowUpRight,Check,ChevronDown,Clock3,Film,Folder,Grid2X2,HelpCircle,Menu,MoreHorizontal,Play,Plus,Search,Settings,SlidersHorizontal,Video,X} from 'lucide-react';
type Aspect='9:16'|'16:9'|'1:1'; type Status='Taslak'|'İşleniyor'|'Tamamlandı'|'Hata';
type Job={id:string;title:string;aspect:Aspect;status:Status;progress:number;created:string;duration:string};
const seed:Job[]=[
 {id:'TK-1048',title:'Kahvenin arkasındaki bilim',aspect:'9:16',status:'Tamamlandı',progress:100,created:'2 Eyl, 14:42',duration:'00:38'},
 {id:'TK-1047',title:'Berlin hafta sonu rehberi',aspect:'9:16',status:'İşleniyor',progress:64,created:'2 Eyl, 13:18',duration:'00:52'},
 {id:'TK-1046',title:'Küçük alışkanlıkların etkisi',aspect:'16:9',status:'Taslak',progress:0,created:'1 Eyl, 18:06',duration:'01:12'},
 {id:'TK-1045',title:'Yapay zekâ ile verimlilik',aspect:'1:1',status:'Tamamlandı',progress:100,created:'1 Eyl, 11:24',duration:'00:45'}];
export function App(){
 const [jobs,setJobs]=useState(seed),[open,setOpen]=useState(false),[nav,setNav]=useState(false);
 const [subject,setSubject]=useState(''),[script,setScript]=useState(''),[aspect,setAspect]=useState<Aspect>('9:16'),[source,setSource]=useState('pexels'),[lang,setLang]=useState('tr'),[voice,setVoice]=useState('tr-TR-EmelNeural-Female'),[subtitles,setSubtitles]=useState(true),[error,setError]=useState('');
 const api=useMemo(()=>String(import.meta.env.VITE_MPT_API_URL||'').replace(/\/$/,''),[]);
 async function createJob(e:React.FormEvent){e.preventDefault();setError('');if(subject.trim().length<4){setError('Konu en az 4 karakter olmalı.');return}
  const item:Job={id:`TK-${1050+jobs.length}`,title:subject.trim(),aspect,status:'İşleniyor',progress:8,created:'Şimdi',duration:'—'};setJobs(v=>[item,...v]);setOpen(false);
  if(!api){setTimeout(()=>setJobs(v=>v.map(j=>j.id===item.id?{...j,status:'Tamamlandı',progress:100,duration:'00:42'}:j)),1800);return}
  try{const r=await fetch(`${api}/api/v1/videos`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({video_subject:subject,video_script:script,video_language:lang,video_aspect:aspect==='9:16'?'portrait':aspect==='16:9'?'landscape':'square',video_source:source,voice_name:voice,subtitle_enabled:subtitles,video_count:1})});if(!r.ok)throw new Error(`API ${r.status}`);const d=await r.json();setJobs(v=>v.map(j=>j.id===item.id?{...j,id:d.data?.task_id||j.id,progress:15}:j))}catch(err){setJobs(v=>v.map(j=>j.id===item.id?{...j,status:'Hata',progress:0}:j));setError(`Motor bağlantısı kurulamadı: ${err instanceof Error?err.message:'Bilinmeyen hata'}`);setOpen(true)}}
 const done=jobs.filter(x=>x.status==='Tamamlandı').length;
 return <div className="app"><aside className={nav?'nav open':'nav'}><div className="logo">T<span>/</span>R<button onClick={()=>setNav(false)}><X/></button></div><div className="workspace"><small>ÇALIŞMA ALANI</small><b>Taskora Studio</b><ChevronDown/></div><nav><a className="selected"><Grid2X2/>Genel bakış</a><a><Film/>Projeler<span>{jobs.length}</span></a><a><Folder/>Varlıklar</a><a><Video/>Şablonlar</a></nav><div className="navBottom"><a><HelpCircle/>Yardım merkezi</a><a><Settings/>Ayarlar</a><div className="user"><div>AK</div><span><b>Ahmet Kaya</b><small>Yönetici</small></span><MoreHorizontal/></div></div></aside>
 <main className="content"><header className="topbar"><button className="mobileMenu" onClick={()=>setNav(true)}><Menu/></button><div className="crumb"><b>Taskora Studio</b><span>/</span><span>Genel bakış</span></div><div className="topActions"><button className="search"><Search/>Ara <kbd>⌘ K</kbd></button><button className="new" onClick={()=>setOpen(true)}><Plus/>Yeni proje</button></div></header>
 <div className="page"><section className="intro"><div><p>2 EYLÜL 2026 · ÇARŞAMBA</p><h1>Üretim masası</h1><span>Videolarınızı tek yerden oluşturun, izleyin ve yönetin.</span></div><div className="availability"><i></i>{api?'Motor bağlı':'Demo çalışma alanı'}</div></section>
 <section className="overview"><article className="createCard"><div><small>YENİ ÜRETİM</small><h2>Bir sonraki videonuz<br/>ne anlatacak?</h2><p>Konuyu yazın; senaryo, ses, görüntü ve altyazı akışını Taskora hazırlasın.</p></div><button onClick={()=>setOpen(true)}>Üretime başla <ArrowUpRight/></button></article><div className="numbers"><article><span>Bu ay</span><strong>{jobs.length}</strong><small>video projesi</small></article><article><span>Tamamlanan</span><strong>{done}</strong><small>indirilmeye hazır</small></article><article><span>Kullanım</span><strong>18<em>dk</em></strong><small>42 dakika kaldı</small><div className="meter"><i></i></div></article></div></section>
 <section className="projects"><div className="projectHead"><div><h3>Son projeler</h3><span>Çalışma alanındaki en son hareketler</span></div><div><button><Search/></button><button><SlidersHorizontal/>Filtrele</button><button>Tümünü gör <ArrowUpRight/></button></div></div><div className="projectTable"><div className="tr th"><span>PROJE</span><span>FORMAT</span><span>SÜRE</span><span>DURUM</span><span>OLUŞTURMA</span><span></span></div>{jobs.map((j,i)=><div className="tr" key={j.id}><span className="projectName"><div className={`cover c${i%4}`}><span>{String(i+1).padStart(2,'0')}</span><Play fill="currentColor"/></div><span><b>{j.title}</b><small>{j.id}</small></span></span><span><i className="format">{j.aspect}</i></span><span>{j.duration}</span><span><i className={`state s-${j.status.toLowerCase()}`}>{j.status==='Tamamlandı'&&<Check/>}{j.status==='İşleniyor'&&<Clock3/>}{j.status}</i>{j.status==='İşleniyor'&&<small className="progress"><i style={{width:`${j.progress}%`}}></i></small>}</span><span>{j.created}</span><span><button className="more" aria-label="Proje seçenekleri"><MoreHorizontal/></button></span></div>)}</div></section></div></main>
 {open&&<div className="overlay" onMouseDown={()=>setOpen(false)}><form className="modal" onSubmit={createJob} onMouseDown={e=>e.stopPropagation()}><div className="modalTop"><div><small>YENİ PROJE</small><h2>Video brifi</h2><p>Üretime başlamak için temel tercihleri belirleyin.</p></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div>{error&&<div className="error">{error}</div>}<label>Video konusu<textarea autoFocus value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Örn. Berlin'de bir hafta sonu nasıl geçirilir?"/></label><label>Senaryo <small>İsteğe bağlı</small><textarea value={script} onChange={e=>setScript(e.target.value)} placeholder="Boş bırakırsanız otomatik hazırlanır."/></label><div className="formGrid"><label>Format<select value={aspect} onChange={e=>setAspect(e.target.value as Aspect)}><option>9:16</option><option>16:9</option><option>1:1</option></select></label><label>Materyal<select value={source} onChange={e=>setSource(e.target.value)}><option value="pexels">Pexels</option><option value="pixabay">Pixabay</option><option value="local">Yerel dosyalar</option></select></label><label>Dil<select value={lang} onChange={e=>setLang(e.target.value)}><option value="tr">Türkçe</option><option value="de">Almanca</option><option value="en">İngilizce</option></select></label><label>Ses<select value={voice} onChange={e=>setVoice(e.target.value)}><option value="tr-TR-EmelNeural-Female">Emel — Kadın</option><option value="tr-TR-AhmetNeural-Male">Ahmet — Erkek</option></select></label></div><label className="toggle"><input type="checkbox" checked={subtitles} onChange={e=>setSubtitles(e.target.checked)}/><i></i><span><b>Otomatik altyazı</b><small>Konuşmayla senkron altyazı oluştur.</small></span></label><div className="modalActions"><button type="button" onClick={()=>setOpen(false)}>Vazgeç</button><button className="submit">Projeyi oluştur <ArrowUpRight/></button></div></form></div>}</div>
}
