import {useMemo,useState} from 'react';
import {Clapperboard,Clock3,Download,Film,LayoutDashboard,Menu,Play,Plus,Search,Settings,Sparkles,Upload,Video,Volume2,X} from 'lucide-react';

type Aspect='9:16'|'16:9'|'1:1';
type Job={id:string;title:string;aspect:Aspect,status:'Hazır'|'Üretiliyor'|'Tamamlandı'|'Hata';progress:number;created:string;url?:string};
const initial:Job[]=[
 {id:'demo-1',title:'Yapay zekâ ile verimliliğin 5 yolu',aspect:'9:16',status:'Tamamlandı',progress:100,created:'Bugün, 14:42'},
 {id:'demo-2',title:'Berlin hafta sonu rehberi',aspect:'9:16',status:'Üretiliyor',progress:64,created:'Bugün, 15:08'},
 {id:'demo-3',title:'Kahvenin arkasındaki bilim',aspect:'16:9',status:'Hazır',progress:0,created:'Dün, 19:21'}
];

export function App(){
 const [jobs,setJobs]=useState<Job[]>(initial); const [open,setOpen]=useState(false); const [mobile,setMobile]=useState(false);
 const [subject,setSubject]=useState(''); const [script,setScript]=useState(''); const [aspect,setAspect]=useState<Aspect>('9:16'); const [source,setSource]=useState('pexels');
 const [lang,setLang]=useState('tr'); const [voice,setVoice]=useState('tr-TR-EmelNeural-Female'); const [subtitles,setSubtitles]=useState(true); const [error,setError]=useState('');
 const done=jobs.filter(j=>j.status==='Tamamlandı').length; const active=jobs.filter(j=>j.status==='Üretiliyor').length;
 const api=useMemo(()=>String(import.meta.env.VITE_MPT_API_URL||'').replace(/\/$/,''),[]);
 async function createJob(e:React.FormEvent){e.preventDefault();setError('');if(subject.trim().length<4){setError('Video konusu en az 4 karakter olmalı.');return}
  const temp:Job={id:crypto.randomUUID(),title:subject.trim(),aspect,status:'Üretiliyor',progress:8,created:'Şimdi'};setJobs(v=>[temp,...v]);setOpen(false);
  if(!api){setTimeout(()=>setJobs(v=>v.map(j=>j.id===temp.id?{...j,progress:100,status:'Tamamlandı'}:j)),1800);return}
  try{const r=await fetch(`${api}/api/v1/videos`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({video_subject:subject,video_script:script,video_language:lang,video_aspect:aspect==='9:16'?'portrait':aspect==='16:9'?'landscape':'square',video_source:source,voice_name:voice,subtitle_enabled:subtitles,video_count:1})});if(!r.ok)throw new Error(`API ${r.status}`);const data=await r.json();setJobs(v=>v.map(j=>j.id===temp.id?{...j,id:data.data?.task_id||j.id,progress:15}:j))}catch(err){setJobs(v=>v.map(j=>j.id===temp.id?{...j,status:'Hata',progress:0}:j));setError(`Motor bağlantısı başarısız: ${err instanceof Error?err.message:'Bilinmeyen hata'}`);setOpen(true)}
 }
 return <div className="shell">
  <aside className={mobile?'side show':'side'}><div className="brand"><span><Sparkles size={19}/></span> taskora<small>STUDIO</small><button className="close" onClick={()=>setMobile(false)}><X/></button></div><nav><a className="active"><LayoutDashboard/>Genel bakış</a><a><Video/>Videolarım</a><a><Clapperboard/>Şablonlar</a><a><Clock3/>Üretim geçmişi</a></nav><div className="sidefoot"><a><Settings/>Ayarlar</a><div className="engine"><i></i><div><b>Video motoru</b><small>{api?'API yapılandırıldı':'Demo modu'}</small></div></div></div></aside>
  <main><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div><h1>İyi akşamlar, Ahmet</h1><p>Bir fikir yaz, yayınlanmaya hazır videoya dönüştür.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus/>Yeni video</button></header>
  <section className="hero"><div className="heroCopy"><span className="eyebrow"><Sparkles/> YAPAY ZEKÂ VİDEO STÜDYOSU</span><h2>Fikrinden videoya,<br/><em>tek bir akışta.</em></h2><p>Senaryoyu oluştur, görüntüleri eşleştir, seslendir ve altyazıları otomatik ekle.</p><button onClick={()=>setOpen(true)}><Play fill="currentColor"/>Video oluşturmaya başla</button></div><div className="phone"><div className="phoneTop"><span></span></div><div className="reel"><div className="glow"></div><span className="reelTag">TASKORA ORIGINAL</span><strong>FİKİRLERİNİ<br/>HAREKETE<br/><i>GEÇİR.</i></strong><div className="caption">Yapay zekâ destekli video üretimi</div><Play className="bigplay" fill="white"/></div></div></section>
  <section className="stats"><article><div className="ico purple"><Film/></div><span>Toplam video<strong>{jobs.length}</strong></span><small>Bu ay</small></article><article><div className="ico green"><Download/></div><span>Tamamlanan<strong>{done}</strong></span><small>Render hazır</small></article><article><div className="ico amber"><Clock3/></div><span>Devam eden<strong>{active}</strong></span><small>İşlem sırasında</small></article></section>
  <section className="recent"><div className="sectionHead"><div><h3>Son projeler</h3><p>Üretimlerini takip et ve çıktıları yönet.</p></div><div className="search"><Search/><input aria-label="Projelerde ara" placeholder="Projelerde ara"/></div></div><div className="table"><div className="row labels"><span>PROJE</span><span>FORMAT</span><span>DURUM</span><span>OLUŞTURMA</span><span></span></div>{jobs.map((j,i)=><div className="row" key={j.id}><span className="project"><b className={`thumb t${i%3}`}><Play fill="white"/></b><span><strong>{j.title}</strong><small>#{j.id.slice(0,8)}</small></span></span><span><span className="pill">{j.aspect}</span></span><span><span className={`status ${j.status.toLowerCase().replace('ı','i')}`}><i></i>{j.status}{j.status==='Üretiliyor'&&` · %${j.progress}`}</span></span><span>{j.created}</span><span><button className="iconbtn" aria-label="İndir"><Download/></button></span></div>)}</div></section>
  </main>
  {open&&<div className="overlay" onMouseDown={()=>setOpen(false)}><form className="modal" onSubmit={createJob} onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><div><span className="modalIcon"><Sparkles/></span><h3>Yeni video oluştur</h3><p>İçeriğini tanımla, gerisini Taskora’ya bırak.</p></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div>{error&&<div className="error">{error}</div>}<label>Video konusu<textarea autoFocus value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Örn. Almanya'da girişimcilere özel 5 vergi ipucu"/></label><label>Özel senaryo <small>(isteğe bağlı)</small><textarea value={script} onChange={e=>setScript(e.target.value)} placeholder="Boş bırakırsan yapay zekâ senaryoyu üretir."/></label><div className="grid2"><label>Format<select value={aspect} onChange={e=>setAspect(e.target.value as Aspect)}><option>9:16</option><option>16:9</option><option>1:1</option></select></label><label>Materyal kaynağı<select value={source} onChange={e=>setSource(e.target.value)}><option value="pexels">Pexels</option><option value="pixabay">Pixabay</option><option value="local">Yerel dosyalar</option></select></label><label>Dil<select value={lang} onChange={e=>setLang(e.target.value)}><option value="tr">Türkçe</option><option value="de">Almanca</option><option value="en">İngilizce</option></select></label><label>Ses<select value={voice} onChange={e=>setVoice(e.target.value)}><option value="tr-TR-EmelNeural-Female">Emel — Kadın</option><option value="tr-TR-AhmetNeural-Male">Ahmet — Erkek</option></select></label></div><label className="check"><input type="checkbox" checked={subtitles} onChange={e=>setSubtitles(e.target.checked)}/><span><b>Otomatik altyazı</b><small>Konuşmayı senkronize altyazıya dönüştür.</small></span></label><div className="actions"><button type="button" onClick={()=>setOpen(false)}>Vazgeç</button><button className="primary"><Sparkles/>Üretimi başlat</button></div></form></div>}
 </div>
}
